### ISSUE TITLE
Currency graph not showing

### ISSUE THREAD

**Issue by MarcoFontana** [viktorgullmark/exilence#73] opened 2018-12-14 17:22 UTC
Hello,

when I use exilence I don't get any graph in the currency section, hiding and reshowing it does not solve the issue and neither does restarting the application, I already uploaded settings to the server from the options

**Comment by viktorgullmark** [comment] 2018-12-14 18:02
Are you sure you have the proper Client.txt-path selected? If you're not sure which one is in use, open the Client.txt-file at the path you have entered in the login-process, and look at the timestamps of the last events in the file. 

This problem usually occurrs because you have an old Client.txt selected, from either an old or uninstalled version of PoE.

**Comment by MarcoFontana** [comment] 2018-12-14 19:48
I double checked and I have the proper client.txt selected, also areas and general currency updates correctly so that does not seem to be the problem.

Should be noted that I had an old client.txt selected the first couple of times I started the application before I changed it to the current one, don't know if that could have caused problems

**Comment by viktorgullmark** [comment] 2018-12-17 09:34
Alright. The old client.txt would not cause this. 

Can you make sure you have stash-tabs selected in settings? By default we select the 10 first. If you don't have 10 tabs in total, this could be the cause of the problem. We're reworking how default-tabs are selected.

**Comment by MarcoFontana** [comment] 2018-12-17 18:13
I have a total of 12 tabs and I selected 4 of them to be tracked, at the start I had the default 10 selected and there was no graph anyway, tonight I'll try to select more and play for a bit to see if that changes anything

**Comment by MarcoFontana** [comment] 2018-12-17 21:07
Selecting more stash tabs did not solve the problem, I also tried to clear the history and try again but to no effect

**Comment by viktorgullmark** [comment] 2018-12-18 08:10
Alright, gotcha. Can you open the console for me and attach a print of it after playing for a few minutes? 

Press `windowsbutton + shift + i` and then press `console` in the top-right. Thanks

**Comment by viktorgullmark** [comment] 2018-12-19 23:48
Closing, contact us on discord if it remains an issue. Most likely due to low resolution after thinking more about this.

**Closed by viktorgullmark** 2018-12-19 23:48 UTC
