### ISSUE TITLE
[CRITICAL BUG] Shortcut is placed on desktop without asking permission

### ISSUE THREAD

**Issue by Artanys** [viktorgullmark/exilence#39] opened 2018-12-07 17:33 UTC
Also, it was added to my startmenu without permission. Generally, these things have some sort of checkbox that allows me to decide:
* where to install it
* if i want a desktop shortcut
* if i want it added to start menu

**Comment by viktorgullmark** [comment] 2018-12-07 17:43
This is not a bug, it's a feature. We use the simplest install possible at the moment. If we feel this is needed we will implement it in the future. Closing.

**Closed by viktorgullmark** 2018-12-07 17:43 UTC
